#!/usr/bin/env bash

cd
git clone https://github.com/holbertonschool/Betty.git
cd Betty
sudo ./install.sh

echo "#!/bin/bash
# Simply a wrapper script to keep you from having to use betty-style
# and betty-doc separately on every item.
# Originally by Tim Britton (@wintermanc3r), multiargument added by
# Larry Madeo (@hillmonkey)

BIN_PATH="/usr/local/bin"
BETTY_STYLE="betty-style"
BETTY_DOC="betty-doc"

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    ${BIN_PATH}/${BETTY_STYLE} "$argument"
    ${BIN_PATH}/${BETTY_DOC} "$argument"
done" > betty

chmod a+x betty

sudo mv betty /bin/


# configuration of .emacs to adapt of betty style

cd

# Tabs configuration
echo "(setq c-default-style "bsd"
     c-basic-offset 8
     tab-width 8
     indent-tabs-mode t)" >> .emacs

# Extension of lines configuration
echo "(require 'whitespace)
(setq whitespace-style '(face empty lines-tail trailing))
(global-whitespace-mode t)" >> .emacs
