#!/usr/bin/env bash

sudo apt-get -y upgrade
sudo apt-get -y update

sudo apt-get -y install python3-dev
sudo apt-get -y install libmysqlclient-dev
sudo apt-get -y install zlib1g-dev
sudo pip3 install mysqlclient
sudo pip3 install mysqlclient==1.3.10

# In case of upgrade error type:
# sudo pip3 install --upgrade mysqlclient
